# Exception ข้อผิดพลาดที่เกิดขึ้นขณะโปรแกรมทำงาน (Runtime Error)
# Exception Handling การจัดการข้อผิดพลาดที่เกิดขึ้นขณะโปรแกรมทำงาน
# Python ใช้ try-except (ภาษาอื่นใช้ try-catch)
 
try :
    num1 = 10
    num2 = 5 # แก้ไขเป็น 0 เพื่อทดสอบข้อผิดพลาด
 
    result = num1 / num2
 
    print("ผลลัพธ์คือ", result)
except : # ทำงานเมื่อข้อผิดพลาดเกิดขึ้น
    print("มีข้อผิดพลาดเกิดขึ้น ลองใหม่อีกครั้ง หรือติดต่อ IT/Support")
else :   # ทำงานเมื่อไม่มีข้อผิดพลาดเกิดขึ้น
    print("คำนวณสำเร็จ ไม่มีข้อผิดพลาดเกิดขึ้น")
finally : # ทำงานเสมอ ไม่ว่าจะเกิดข้อผิดพลาดหรือไม่
    print("Thank you")